config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # resource :user, only: [:show]

  # rootをログイン画面に設定
  devise_scope :user do
    root "users/sessions#new"
    get '/users/sign_out' => 'devise/sessions#destroy'
    
  end

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :confirmations => 'users/confirmations',
    :passwords => 'users/passwords'
  } 

  namespace :users do
    get 'dash_boards'
    resources :articles
  end
  
  #開発環境のみletter_openerのURLを追加
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :user
	mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable, :confirmable
  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	def after_sign_in_path_for(resource)
    users_dash_boards_path(resource)
  end
end

app/controllers/users/articles_controller.rb
class Users::ArticlesController < ApplicationController
	before_action :sign_in_user

	def index
		@user = User.find(current_user.id)
		@articles = @user.articles.all
	end

	def show
		@user = User.find(current_user.id)
		@article = @user.articles.find(params[:id])
	end

	def new
		@article = Article.new
	end

	def create
		@user = User.find(current_user.id)
		@article = @user.articles.new(article_params)
		@article.save!
		redirect_to users_article_path(@article)
	end

	def edit
		@user = User.find(current_user.id)
		@article = @user.articles.find(params[:id])
	end

	def update
		@user = User.find(current_user.id)
		@article = @user.articles.find(params[:id])
		@article.update!(article_params)
		redirect_to users_article_path(@article)
	end
	
  def destroy
    Article.find(params[:id]).destroy
    flash[:success] = "記事を削除しました"
    redirect_to users_articles_url
  end
	

private
	def article_params
		params.require(:article).permit(:title, :content, :image, :remove_image)
	end

	def sign_in_user
		redirect_to root_path, alert: 'ログインしてください' unless current_user.present?
	end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    # super
    build_resource(sign_up_params)
    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def dash_boards
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users/articles_helper.rb
module Users::ArticlesHelper

	def btn_text
    if action_name == "new"
      "新規作成"
    elsif action_name == "edit"
      "更新する"
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |message_type, message| %>
      <div class="text-center"><%= content_tag :div, message, class: message_type %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/articles/_form.html.erb
<%= form_with model: [:users, @article] do |f| %>
	<%# render "users/shared/error_messages", resource: resource %>
	<div class="field">
		<%= f.label :title, class:"offset-md-2"%><br />
		<%= f.text_field :title, autofocus: true, autocomplete: "title", class:"col-md-8 offset-md-2" %>
	</div>

	<div class="field">
		<%= f.label :content, class:"offset-md-2" %><br />
		<%= f.text_area :content, autofocus: true, class:"col-md-8 offset-md-2" %>
	</div>

	<div class="field">
		<%= f.label :image, class:"offset-md-2" %>
		<%= f.file_field :image, class:"col-md-8 offset-md-2"  %>
	</div>

	<div class="actions text-center m-4">
		<%= f.submit btn_text, class: "btn btn-primary" %>
	</div>

	<div class="offset-md-2">
		<%= link_to "戻る", :back %>
	</div>
<% end %>

app/views/users/articles/edit.html.erb
<div class='row'>
	<div class='container'>
		<div class='col-md-6 offset-md-3'>
		<h2 class='text-center'>記事の編集</h2>
		<%= render partial: 'form', locals: { article: @article } %>
	</div>
</div>

app/views/users/articles/index.html.erb
<div class='container'>
	<div class='row'>
		<div class='col-md-10 offset-md-1'>
			<h2 class="text-center">記事一覧</h2>
			<%= link_to "記事新規作成", new_users_article_path, class:"btn btn-primary col-md-6 offset-md-3" %>
			<table class='table'>
				<thead>
					<tr class='text-center'>
						<th>詳細表示</th>
						<th>タイトル</th>
						<th>内容</th>
						<th>画像</th>
						<th>編集・削除</th>
					</tr>
				</thead>
				<tbody>
					<% @articles.each do |article| %>
						<tr class='text-center'>
							<td><%= link_to "詳細", users_article_url(article), class: 'btn btn-primary' %></td>
							<td><%= article.title %></td>
							<td><%= article.content %></td>
							<td>
								<% if article.image? %>  <!-- アップロード画像がある場合に実行する -->
									<%= image_tag article.image.url %><!-- userインスタンスの画像ファイルのURLを取得し表示 -->
								<% end %>
							</td>
							<td>
								<%= link_to "編集", edit_users_article_url(article), class:'btn btn-success' %>
								<%= link_to "削除", [:users, article], method: :delete,
																												data: { confirm: "You sure?" }, class: 'btn btn-danger' %>
							</td>
						</tr>
					<% end%>
				</tbody>
			</table>
		<div class='text-center'>
			<%= link_to "ダッシュボードへ戻る", users_dash_boards_url, class:'btn btn-success' %>
		</div>
	</div>
</div>

app/views/users/articles/new.html.erb
<div class='row'>
	<div class='container'>
		<div class='col-md-6 offset-md-3'>
		<h2 class='text-center'>記事の新規作成</h2>
		<%= render partial: 'form', locals: { article: @article } %>
	</div>
</div>

app/views/users/articles/show.html.erb
<div class='container'>
	<div class='row'>
		<div class='col-md-10 offset-md-1'>
			<h2 class="text-center">記事詳細</h2>
			<table class='table'>
				<thead>
					<tr class='text-center'>
						<th>タイトル</th>
						<th>内容</th>
						<th>画像</th>
					</tr>
				</thead>
				<tbody>
					<tr class='text-center'>
						<td><%= @article.title %></td>
						<td><%= @article.content %></td>
						<td>
						<% if @article.image? %>  <!-- アップロード画像がある場合に実行する -->
								<%= image_tag @article.image.url %><!-- userインスタンスの画像ファイルのURLを取得し表示 -->
						<% end %>
						</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
	<div class='row'>
		<div class='col-md-6 offset-md-3 text-center'>
			<%= link_to "編集", edit_users_article_url(@article), class:'btn btn-success' %>
			<%= link_to "削除", [:users, @article], method: :delete,
																						data: { confirm: "You sure?" }, class: 'btn btn-danger' %>
		</div>
	</div>
	<div class="text-center">
		<%= link_to "記事一覧へ戻る", users_articles_path, class: "btn btn-primary m-4" %>
	</div>
</div>

app/views/users/dash_boards.html.erb
<h2 class="text-center">Dash Boards</h2>
<h4 class="text-center"><%= current_user.name %></h4>
<div class= "container">
	<div class="row col-md-6 offset-md-3">
		<%= link_to "記事一覧", users_articles_path, class: "btn btn-primary col-md-6 offset-md-3 mt-3" %>
		<%= link_to "編集", edit_user_registration_path, class: "btn btn-primary col-md-6 offset-md-3 mt-3" %>
		<%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn btn-warning col-md-6 offset-md-3 mt-3" %>
	</div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                count: resource.errors.count,
                resource: resource.class.model_name.human.downcase)
      %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to t('.sign_in'), new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to t('.sign_up'), new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to t('.forgot_your_password'), new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to t('.didn_t_receive_confirmation_instructions'), new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to t('.didn_t_receive_unlock_instructions'), new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>